# Generated by Django 2.2.4 on 2020-05-25 21:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonexam_app', '0002_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='quote',
            new_name='message',
        ),
    ]
