# Generated by Django 2.2.4 on 2020-05-25 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonexam_app', '0003_auto_20200525_2147'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='message',
            new_name='quotemessage',
        ),
    ]
